# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ukJoy6DXWdPN_hWpDj09JEBlQEHns5fA
"""


import re
import string
import numpy as np
import pandas as pd

from pypdf import PdfReader
from docx import Document

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

import nltk
from nltk.corpus import stopwords

nltk.download("stopwords")

STOP_WORDS = set(stopwords.words("english"))

print("✅ All libraries imported successfully!")

from google.colab import files

uploaded = files.upload()

file_name = list(uploaded.keys())[0]

print("Uploaded file:", file_name)

if file_name.lower().endswith(".pdf"):

    reader = PdfReader(file_name)

    resume_text = ""

    for page in reader.pages:
        text = page.extract_text()

        if text:
            resume_text += text + "\n"

elif file_name.lower().endswith(".docx"):

    document = Document(file_name)

    resume_text = ""

    for paragraph in document.paragraphs:
        resume_text += paragraph.text + "\n"

else:
    raise ValueError("Please upload a PDF or DOCX file.")

print("\n========== RESUME TEXT ==========\n")
print(resume_text)

def clean_text(text):

    # Convert everything to lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r'http\S+|www\S+', ' ', text)

    # Remove email addresses
    text = re.sub(r'\S+@\S+', ' ', text)

    # Remove numbers
    text = re.sub(r'\d+', ' ', text)

    # Remove punctuation
    text = text.translate(
        str.maketrans('', '', string.punctuation)
    )

    # Split into words
    words = text.split()

    # Remove stopwords
    words = [
        word for word in words
        if word not in STOP_WORDS
    ]

    # Join words back together
    cleaned_text = " ".join(words)

    return cleaned_text


cleaned_resume = clean_text(resume_text)

print("========== CLEANED RESUME ==========\n")
print(cleaned_resume)

job_description = """
We are looking for a Data Analyst who has strong knowledge
of Python, SQL, Excel, Power BI and Tableau.

The candidate should have experience in data analysis,
data visualization, statistics, machine learning and
working with large datasets.

Knowledge of Pandas, NumPy and scikit-learn is preferred.
"""

print(job_description)

cleaned_job = clean_text(job_description)

print("========== CLEANED JOB DESCRIPTION ==========\n")
print(cleaned_job)

vectorizer = TfidfVectorizer()

documents = [
    cleaned_resume,
    cleaned_job
]

tfidf_matrix = vectorizer.fit_transform(documents)

print("TF-IDF Matrix Shape:", tfidf_matrix.shape)

similarity = cosine_similarity(
    tfidf_matrix[0:1],
    tfidf_matrix[1:2]
)

similarity_score = similarity[0][0] * 100

print(f"Resume–Job Similarity: {similarity_score:.2f}%")

skills = [
    # Programming
    "python",
    "java",
    "r",
    "c++",

    # Databases
    "sql",
    "mysql",
    "postgresql",
    "mongodb",

    # Data Analysis
    "excel",
    "power bi",
    "tableau",
    "pandas",
    "numpy",

    # Machine Learning
    "machine learning",
    "deep learning",
    "scikit-learn",
    "tensorflow",
    "pytorch",

    # Statistics
    "statistics",
    "hypothesis testing",
    "regression",
    "probability",

    # Data / AI
    "data analysis",
    "data visualization",
    "nlp",
    "artificial intelligence",

    # Cloud
    "aws",
    "azure",
    "google cloud",

    # Tools
    "git",
    "github",
    "docker"
]

print("Total skills in database:", len(skills))

def extract_skills(text):

    text = text.lower()

    found_skills = []

    for skill in skills:

        if skill in text:
            found_skills.append(skill)

    return sorted(set(found_skills))

resume_skills = extract_skills(resume_text)

print("========== RESUME SKILLS ==========\n")

for skill in resume_skills:
    print("✓", skill)

job_skills = extract_skills(job_description)

print("========== REQUIRED JOB SKILLS ==========\n")

for skill in job_skills:
    print("•", skill)

matched_skills = sorted(
    set(resume_skills) &
    set(job_skills)
)

print("========== MATCHED SKILLS ==========\n")

for skill in matched_skills:
    print("✓", skill)

missing_skills = sorted(
    set(job_skills) -
    set(resume_skills)
)

print("========== MISSING SKILLS ==========\n")

for skill in missing_skills:
    print("✗", skill)

if len(job_skills) > 0:

    skill_score = (
        len(matched_skills) /
        len(job_skills)
    ) * 100

else:

    skill_score = 0

print(f"Skill Match Score: {skill_score:.2f}%")

# Text similarity score from Step 7
text_score = similarity_score

# Skill score from Step 8
skill_score = skill_score

# Weighted final score
final_score = (
    (text_score * 0.60) +
    (skill_score * 0.40)
)

print("========== FINAL RESULT ==========\n")

print(f"Text Similarity Score : {text_score:.2f}%")
print(f"Skill Match Score     : {skill_score:.2f}%")
print(f"Final Match Score     : {final_score:.2f}%")

def get_recommendation(score):

    if score >= 80:
        return "Excellent Match - Strongly Recommended"

    elif score >= 65:
        return "Good Match - Recommended"

    elif score >= 50:
        return "Moderate Match - Consider Improving Skills"

    else:
        return "Low Match - Significant Skill Gaps"


recommendation = get_recommendation(final_score)

print("Recommendation:", recommendation)

print("=" * 60)
print("             AI RESUME MATCHING REPORT")
print("=" * 60)

print(f"\n📊 Text Similarity     : {text_score:.2f}%")
print(f"🛠️ Skill Match          : {skill_score:.2f}%")
print(f"🎯 Overall Match       : {final_score:.2f}%")

print("\n✅ MATCHED SKILLS")
print("-" * 30)

for skill in matched_skills:
    print("✓", skill)

print("\n❌ MISSING SKILLS")
print("-" * 30)

for skill in missing_skills:
    print("✗", skill)

print("\n💡 RECOMMENDATION")
print("-" * 30)

print(recommendation)

print("\n" + "=" * 60)

candidate_resumes = {

    "Candidate 1": """
    Data Analyst with experience in Python, SQL, Excel,
    Power BI, Pandas, NumPy and statistics.
    Experienced in data analysis and data visualization.
    """,

    "Candidate 2": """
    Business Analyst skilled in Excel, SQL, Tableau,
    Power BI and statistics.
    Experienced in reporting and business intelligence.
    """,

    "Candidate 3": """
    Data Scientist with Python, SQL, Pandas, NumPy,
    Machine Learning, Scikit-learn, statistics and
    data visualization.
    """
}

print("Number of candidates:", len(candidate_resumes))

def calculate_candidate_score(resume, job):

    # Clean text
    resume_clean = clean_text(resume)
    job_clean = clean_text(job)

    # TF-IDF
    vectorizer = TfidfVectorizer()

    matrix = vectorizer.fit_transform([
        resume_clean,
        job_clean
    ])

    similarity = cosine_similarity(
        matrix[0:1],
        matrix[1:2]
    )[0][0] * 100

    # Skills
    resume_skills = extract_skills(resume)
    job_skills = extract_skills(job)

    matched = sorted(
        set(resume_skills) &
        set(job_skills)
    )

    missing = sorted(
        set(job_skills) -
        set(resume_skills)
    )

    # Skill score
    if len(job_skills) > 0:

        skill_score = (
            len(matched) /
            len(job_skills)
        ) * 100

    else:

        skill_score = 0

    # Final score
    final_score = (
        similarity * 0.60 +
        skill_score * 0.40
    )

    return {
        "Text Similarity": round(similarity, 2),
        "Skill Match": round(skill_score, 2),
        "Final Score": round(final_score, 2),
        "Matched Skills": matched,
        "Missing Skills": missing
    }

ranking = []

for candidate, resume in candidate_resumes.items():

    result = calculate_candidate_score(
        resume,
        job_description
    )

    ranking.append({
        "Candidate": candidate,
        "Text Similarity": result["Text Similarity"],
        "Skill Match": result["Skill Match"],
        "Final Score": result["Final Score"]
    })


ranking_df = pd.DataFrame(ranking)

ranking_df = ranking_df.sort_values(
    by="Final Score",
    ascending=False
).reset_index(drop=True)

ranking_df.index = ranking_df.index + 1

print(ranking_df)

ranking_df

top_candidate = ranking_df.iloc[0]

print("🏆 TOP CANDIDATE")
print("-" * 40)

print("Candidate:", top_candidate["Candidate"])
print("Final Score:", top_candidate["Final Score"], "%")

for candidate, resume in candidate_resumes.items():

    result = calculate_candidate_score(
        resume,
        job_description
    )

    print("\n" + "=" * 50)
    print(candidate)
    print("=" * 50)

    print(
        "Final Score:",
        result["Final Score"],
        "%"
    )

    print("\n✅ Matched Skills:")

    for skill in result["Matched Skills"]:
        print("  ✓", skill)

    print("\n❌ Missing Skills:")

    for skill in result["Missing Skills"]:
        print("  ✗", skill)

from google.colab import files

uploaded_resumes = files.upload()

print("\nUploaded resumes:")
for file_name in uploaded_resumes.keys():
    print("📄", file_name)

candidate_texts = {}

for file_name in uploaded_resumes.keys():

    try:

        if file_name.lower().endswith(".pdf"):

            reader = PdfReader(file_name)

            text = ""

            for page in reader.pages:

                page_text = page.extract_text()

                if page_text:
                    text += page_text + "\n"

        elif file_name.lower().endswith(".docx"):

            document = Document(file_name)

            text = ""

            for paragraph in document.paragraphs:
                text += paragraph.text + "\n"

        else:

            print(f"⚠️ Skipping unsupported file: {file_name}")
            continue

        candidate_texts[file_name] = text

        print(f"✅ Extracted: {file_name}")

    except Exception as e:

        print(f"❌ Error reading {file_name}: {e}")

for file_name, text in candidate_texts.items():

    print("\n" + "=" * 60)
    print("📄", file_name)
    print("=" * 60)

    print(text[:500])

real_ranking = []

for file_name, resume_text in candidate_texts.items():

    result = calculate_candidate_score(
        resume_text,
        job_description
    )

    real_ranking.append({

        "Resume": file_name,

        "Text Similarity":
            result["Text Similarity"],

        "Skill Match":
            result["Skill Match"],

        "Final Score":
            result["Final Score"],

        "Matched Skills":
            ", ".join(result["Matched Skills"]),

        "Missing Skills":
            ", ".join(result["Missing Skills"])
    })


real_ranking_df = pd.DataFrame(real_ranking)

real_ranking_df = real_ranking_df.sort_values(
    by="Final Score",
    ascending=False
).reset_index(drop=True)

real_ranking_df.index = real_ranking_df.index + 1

real_ranking_df

best_candidate = real_ranking_df.iloc[0]

print("🏆 BEST MATCH")
print("=" * 50)

print("Resume:", best_candidate["Resume"])
print("Final Score:", best_candidate["Final Score"], "%")

print("\n✅ Matched Skills:")
print(best_candidate["Matched Skills"])

print("\n❌ Missing Skills:")
print(best_candidate["Missing Skills"])

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))

plt.bar(
    real_ranking_df["Resume"],
    real_ranking_df["Final Score"]
)

plt.xlabel("Candidates")
plt.ylabel("Final Match Score (%)")
plt.title("Resume Match Score by Candidate")

plt.xticks(rotation=45)
plt.ylim(0, 100)

plt.show()

comparison_df = real_ranking_df[
    ["Resume", "Text Similarity", "Skill Match"]
].copy()

comparison_df

comparison_df.plot(
    x="Resume",
    y=["Text Similarity", "Skill Match"],
    kind="bar",
    figsize=(10, 5)
)

plt.title("Text Similarity vs Skill Match")
plt.xlabel("Candidates")
plt.ylabel("Score (%)")
plt.xticks(rotation=45)

plt.ylim(0, 100)

plt.show()

from collections import Counter

missing_skill_counter = Counter()

for file_name, resume_text in candidate_texts.items():

    result = calculate_candidate_score(
        resume_text,
        job_description
    )

    for skill in result["Missing Skills"]:

        missing_skill_counter[skill] += 1


missing_skills_df = pd.DataFrame(
    missing_skill_counter.items(),
    columns=["Skill", "Candidates Missing"]
)

missing_skills_df = missing_skills_df.sort_values(
    by="Candidates Missing",
    ascending=False
)

missing_skills_df

plt.figure(figsize=(8, 5))

plt.bar(
    missing_skills_df["Skill"],
    missing_skills_df["Candidates Missing"]
)

plt.xlabel("Skill")
plt.ylabel("Number of Candidates")
plt.title("Most Common Missing Skills")

plt.xticks(rotation=45)

plt.show()

final_report = real_ranking_df[
    [
        "Resume",
        "Text Similarity",
        "Skill Match",
        "Final Score",
        "Matched Skills",
        "Missing Skills"
    ]
].copy()

final_report

!pip install streamlit pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import re
# import string
# 
# from pypdf import PdfReader
# from docx import Document
# 
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.metrics.pairwise import cosine_similarity
# 
# import nltk
# from nltk.corpus import stopwords
# 
# nltk.download("stopwords", quiet=True)
# 
# STOP_WORDS = set(stopwords.words("english"))
# 
# # ============================================================
# # SKILL DATABASE
# # ============================================================
# 
# skills = [
#     "python",
#     "java",
#     "r",
#     "c++",
# 
#     "sql",
#     "mysql",
#     "postgresql",
#     "mongodb",
# 
#     "excel",
#     "power bi",
#     "tableau",
#     "pandas",
#     "numpy",
# 
#     "machine learning",
#     "deep learning",
#     "scikit-learn",
#     "tensorflow",
#     "pytorch",
# 
#     "statistics",
#     "hypothesis testing",
#     "regression",
#     "probability",
# 
#     "data analysis",
#     "data visualization",
#     "nlp",
#     "artificial intelligence",
# 
#     "aws",
#     "azure",
#     "google cloud",
# 
#     "git",
#     "github",
#     "docker"
# ]
# 
# 
# # ============================================================
# # TEXT EXTRACTION
# # ============================================================
# 
# def extract_pdf_text(uploaded_file):
# 
#     reader = PdfReader(uploaded_file)
# 
#     text = ""
# 
#     for page in reader.pages:
# 
#         page_text = page.extract_text()
# 
#         if page_text:
#             text += page_text + "\n"
# 
#     return text
# 
# 
# def extract_docx_text(uploaded_file):
# 
#     document = Document(uploaded_file)
# 
#     text = ""
# 
#     for paragraph in document.paragraphs:
# 
#         text += paragraph.text + "\n"
# 
#     return text
# 
# 
# def extract_text(uploaded_file):
# 
#     file_name = uploaded_file.name.lower()
# 
#     if file_name.endswith(".pdf"):
# 
#         return extract_pdf_text(uploaded_file)
# 
#     elif file_name.endswith(".docx"):
# 
#         return extract_docx_text(uploaded_file)
# 
#     else:
# 
#         return ""
# 
# 
# # ============================================================
# # TEXT CLEANING
# # ============================================================
# 
# def clean_text(text):
# 
#     text = text.lower()
# 
#     text = re.sub(
#         r'http\S+|www\S+',
#         ' ',
#         text
#     )
# 
#     text = re.sub(
#         r'\S+@\S+',
#         ' ',
#         text
#     )
# 
#     text = re.sub(
#         r'\d+',
#         ' ',
#         text
#     )
# 
#     text = text.translate(
#         str.maketrans(
#             '',
#             '',
#             string.punctuation
#         )
#     )
# 
#     words = text.split()
# 
#     words = [
#         word
#         for word in words
#         if word not in STOP_WORDS
#     ]
# 
#     return " ".join(words)
# 
# 
# # ============================================================
# # SKILL EXTRACTION
# # ============================================================
# 
# def extract_skills(text):
# 
#     text = text.lower()
# 
#     found_skills = []
# 
#     for skill in skills:
# 
#         if skill in text:
# 
#             found_skills.append(skill)
# 
#     return sorted(set(found_skills))
# 
# 
# # ============================================================
# # RESUME MATCHING
# # ============================================================
# 
# def calculate_candidate_score(resume, job):
# 
#     resume_clean = clean_text(resume)
# 
#     job_clean = clean_text(job)
# 
#     # TF-IDF
#     vectorizer = TfidfVectorizer()
# 
#     matrix = vectorizer.fit_transform(
#         [resume_clean, job_clean]
#     )
# 
#     similarity = cosine_similarity(
#         matrix[0:1],
#         matrix[1:2]
#     )[0][0] * 100
# 
#     # Skills
#     resume_skills = extract_skills(resume)
# 
#     job_skills = extract_skills(job)
# 
#     matched = sorted(
#         set(resume_skills) &
#         set(job_skills)
#     )
# 
#     missing = sorted(
#         set(job_skills) -
#         set(resume_skills)
#     )
# 
#     # Skill score
#     if len(job_skills) > 0:
# 
#         skill_score = (
#             len(matched) /
#             len(job_skills)
#         ) * 100
# 
#     else:
# 
#         skill_score = 0
# 
#     # Final weighted score
#     final_score = (
#         similarity * 0.60 +
#         skill_score * 0.40
#     )
# 
#     return {
#         "Text Similarity": round(similarity, 2),
#         "Skill Match": round(skill_score, 2),
#         "Final Score": round(final_score, 2),
#         "Matched Skills": matched,
#         "Missing Skills": missing
#     }
# 
# 
# # ============================================================
# # STREAMLIT UI
# # ============================================================
# 
# st.set_page_config(
#     page_title="AI Resume Matcher",
#     page_icon="📄",
#     layout="wide"
# )
# 
# st.title("📄 AI Resume–Job Matching System")
# 
# st.write(
#     "Upload multiple resumes and compare them "
#     "against a job description using NLP and Machine Learning."
# )
# 
# st.divider()
# 
# # ------------------------------------------------------------
# # Upload resumes
# # ------------------------------------------------------------
# 
# st.subheader("📂 Upload Resumes")
# 
# uploaded_resumes = st.file_uploader(
#     "Upload candidate resumes",
#     type=["pdf", "docx"],
#     accept_multiple_files=True
# )
# 
# # ------------------------------------------------------------
# # Job description
# # ------------------------------------------------------------
# 
# st.subheader("💼 Job Description")
# 
# job_description = st.text_area(
#     "Paste the job description here:",
#     height=250
# )
# 
# # ------------------------------------------------------------
# # Analyze
# # ------------------------------------------------------------
# 
# if st.button(
#     "🚀 Analyze Candidates",
#     type="primary"
# ):
# 
#     if not uploaded_resumes:
# 
#         st.error(
#             "Please upload at least one resume."
#         )
# 
#     elif not job_description.strip():
# 
#         st.error(
#             "Please enter a job description."
#         )
# 
#     else:
# 
#         results = []
# 
#         detailed_results = {}
# 
#         # ----------------------------------------
#         # Process each resume
#         # ----------------------------------------
# 
#         for resume_file in uploaded_resumes:
# 
#             try:
# 
#                 resume_text = extract_text(
#                     resume_file
#                 )
# 
#                 if not resume_text.strip():
# 
#                     st.warning(
#                         f"Could not extract text from {resume_file.name}"
#                     )
# 
#                     continue
# 
#                 result = calculate_candidate_score(
#                     resume_text,
#                     job_description
#                 )
# 
#                 results.append({
# 
#                     "Resume":
#                         resume_file.name,
# 
#                     "Text Similarity":
#                         result["Text Similarity"],
# 
#                     "Skill Match":
#                         result["Skill Match"],
# 
#                     "Final Score":
#                         result["Final Score"]
#                 })
# 
#                 detailed_results[
#                     resume_file.name
#                 ] = result
# 
#             except Exception as e:
# 
#                 st.error(
#                     f"Error processing {resume_file.name}: {e}"
#                 )
# 
#         # ----------------------------------------
#         # Ranking
#         # ----------------------------------------
# 
#         if results:
# 
#             import pandas as pd
# 
#             ranking_df = pd.DataFrame(
#                 results
#             )
# 
#             ranking_df = ranking_df.sort_values(
#                 by="Final Score",
#                 ascending=False
#             ).reset_index(drop=True)
# 
#             ranking_df.index += 1
# 
#             st.divider()
# 
#             # ------------------------------------
#             # Top candidate
#             # ------------------------------------
# 
#             top_candidate = ranking_df.iloc[0]
# 
#             st.subheader("🏆 Best Candidate")
# 
#             col1, col2, col3 = st.columns(3)
# 
#             col1.metric(
#                 "Candidate",
#                 top_candidate["Resume"]
#             )
# 
#             col2.metric(
#                 "Overall Match",
#                 f'{top_candidate["Final Score"]:.2f}%'
#             )
# 
#             col3.metric(
#                 "Skill Match",
#                 f'{top_candidate["Skill Match"]:.2f}%'
#             )
# 
#             # ------------------------------------
#             # Ranking table
#             # ------------------------------------
# 
#             st.subheader("📊 Candidate Ranking")
# 
#             st.dataframe(
#                 ranking_df,
#                 use_container_width=True
#             )
# 
#             # ------------------------------------
#             # Chart
#             # ------------------------------------
# 
#             st.subheader("📈 Match Score Comparison")
# 
#             chart_data = ranking_df.set_index(
#                 "Resume"
#             )[["Final Score"]]
# 
#             st.bar_chart(
#                 chart_data
#             )
# 
#             # ------------------------------------
#             # Candidate details
#             # ------------------------------------
# 
#             st.subheader(
#                 "🔍 Candidate Skill Analysis"
#             )
# 
#             selected_candidate = st.selectbox(
#                 "Select a candidate:",
#                 ranking_df["Resume"].tolist()
#             )
# 
#             selected_result = detailed_results[
#                 selected_candidate
#             ]
# 
#             col1, col2 = st.columns(2)
# 
#             with col1:
# 
#                 st.markdown(
#                     "### ✅ Matched Skills"
#                 )
# 
#                 if selected_result[
#                     "Matched Skills"
#                 ]:
# 
#                     for skill in selected_result[
#                         "Matched Skills"
#                     ]:
# 
#                         st.write(
#                             f"✓ {skill}"
#                         )
# 
#                 else:
# 
#                     st.write(
#                         "No matching skills found."
#                     )
# 
#             with col2:
# 
#                 st.markdown(
#                     "### ❌ Missing Skills"
#                 )
# 
#                 if selected_result[
#                     "Missing Skills"
#                 ]:
# 
#                     for skill in selected_result[
#                         "Missing Skills"
#                     ]:
# 
#                         st.write(
#                             f"✗ {skill}"
#                         )
# 
#                 else:
# 
#                     st.write(
#                         "No major missing skills."
#                     )
# 
#             # ------------------------------------
#             # Recommendation
#             # ------------------------------------
# 
#             score = selected_result[
#                 "Final Score"
#             ]
# 
#             st.subheader(
#                 "💡 Recommendation"
#             )
# 
#             if score >= 80:
# 
#                 st.success(
#                     "Excellent Match — Strongly Recommended"
#                 )
# 
#             elif score >= 65:
# 
#                 st.info(
#                     "Good Match — Recommended"
#                 )
# 
#             elif score >= 50:
# 
#                 st.warning(
#                     "Moderate Match — Consider Improving Skills"
#                 )
# 
#             else:
# 
#                 st.error(
#                     "Low Match — Significant Skill Gaps"
#                 )

!streamlit run app.py &>/content/logs.txt &

!cat /content/logs.txt

!pip install pyngrok -q

from google.colab import userdata
import os

os.environ["NGROK_AUTHTOKEN"] = userdata.get("NGROK_AUTHTOKEN")

print("✅ Token loaded")

from pyngrok import ngrok

public_url = ngrok.connect(8501)

print("🌐 Your Resume Matching App:")
print(public_url)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# 
# streamlit
# pypdf
# python-docx
# scikit-learn
# pandas
# numpy
# nltk
# pyngrok

from google.colab import files

files.download("requirements.txt")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile README.md
# 
# # 🤖 AI Resume–Job Matching System
# 
# An NLP-based Resume Matching System that compares candidate resumes with a job description, calculates an overall matching score, identifies matched and missing skills, and ranks multiple candidates based on their suitability for the role.
# 
# ## 📌 Project Overview
# 
# Recruiters often receive a large number of resumes for a single job opening. Manually reviewing every resume can be time-consuming.
# 
# This project automates the initial resume screening process using Natural Language Processing and Machine Learning techniques.
# 
# The system analyzes resumes against a job description and provides:
# 
# - Resume-to-job similarity score
# - Skill match percentage
# - Matched skills
# - Missing skills
# - Overall candidate score
# - Candidate ranking
# - Candidate recommendations
# 
# ## 🚀 Features
# 
# - 📄 Upload PDF and DOCX resumes
# - 🧹 Resume text preprocessing
# - 🧠 TF-IDF text vectorization
# - 🔍 Cosine similarity
# - 🛠️ Automated skill extraction
# - ✅ Matched skill identification
# - ❌ Missing skill identification
# - 🎯 Weighted overall match score
# - 🏆 Multiple candidate ranking
# - 📊 Candidate comparison
# - 🌐 Streamlit web application
# 
# ## 🧠 Technologies Used
# 
# | Technology | Purpose |
# |---|---|
# | Python | Main programming language |
# | Pandas | Data processing |
# | NumPy | Numerical operations |
# | NLTK | Natural Language Processing |
# | Scikit-learn | TF-IDF and Cosine Similarity |
# | PyPDF | PDF text extraction |
# | python-docx | DOCX text extraction |
# | Streamlit | Web application |
# 
# ## ⚙️ System Workflow
# 
# ```text
# Resume PDF / DOCX
#         ↓
# Text Extraction
#         ↓
# Text Cleaning
#         ↓
# TF-IDF Vectorization
#         ↓
# Cosine Similarity
#         ↓
# Skill Extraction
#         ↓
# Skill Matching
#         ↓
# Weighted Match Score
#         ↓
# Candidate Ranking
#         ↓
# Streamlit Dashboard

from google.colab import files

files.download("README.md")

!streamlit run app.py &>/content/logs.txt &

from pyngrok import ngrok

ngrok.kill()

public_url = ngrok.connect(8501)

print("🌐 New app URL:")
print(public_url)

!streamlit run app.py &>/content/logs.txt &

from pyngrok import ngrok

ngrok.kill()

public_url = ngrok.connect(8501)

print("🌐 New Resume Matching App URL:")
print(public_url)

!ps aux | grep streamlit

!cat /content/log.txt

!pkill -f streamlit

!streamlit run app.py --server.port 8501 > /content/log.txt 2>&1 &

!cat /content/log.txt

!curl -I http://localhost:8501

from pyngrok import ngrok

# Close old tunnels
ngrok.kill()

# Create a new tunnel
tunnel = ngrok.connect(8501)

print("🌐 Your AI Resume Matching App:")
print(tunnel.public_url)

